export const CountryCodes = new Map([
    ["ZW", "Zimbabwe"],
    ["ZM", "Zambia"],
    ["YE", "Yemen"],
    ["VN", "Vietnam"],
    ["VE", "Venezuela"],
    ["VA", "Vatican"],
    ["VU", "Vanuatu"],
    ["UZ", "Uzbekistan"],
    ["UY", "Uruguay"],
    ["FM", "Micronesia"],
    ["MH", "Marshall Is."],
    ["MP", "N. Mariana Is."],
    ["VI", "U.S. Virgin Is."],
    ["GU", "Guam"],
    ["AS", "American Samoa"],
    ["PR", "Puerto Rico"],
    ["US", "United States of America"],
    ["", "S. Geo. and the Is."],
    ["IO", "Br. Indian Ocean Ter."],
    ["SH", "Saint Helena"],
    ["PN", "Pitcairn Is."],
    ["AI", "Anguilla"],
    ["FK", "Falkland Is."],
    ["KY", "Cayman Is."],
    ["BM", "Bermuda"],
    ["VG", "British Virgin Is."],
    ["TC", "Turks and Caicos Is."],
    ["MS", "Montserrat"],
    ["JE", "Jersey"],
    ["GG", "Guernsey"],
    ["IM", "Isle of Man"],
    ["GB", "United Kingdom"],
    ["AE", "United Arab Emirates"],
    ["UA", "Ukraine"],
    ["UG", "Uganda"],
    ["TM", "Turkmenistan"],
    ["TR", "Turkey"],
    ["TN", "Tunisia"],
    ["TT", "Trinidad and Tobago"],
    ["TO", "Tonga"],
    ["TG", "Togo"],
    ["TL", "Timor-Leste"],
    ["TH", "Thailand"],
    ["TZ", "Tanzania"],
    ["TJ", "Tajikistan"],
    ["TW", "Taiwan"],
    ["SY", "Syria"],
    ["CH", "Switzerland"],
    ["SE", "Sweden"],
    ["", "eSwatini"],
    ["SR". "Suriname"],
    ["SS", "S. Sudan"],
    ["SD", "Sudan"],
    ["LK", "Sri Lanka"],
    ["ES", "Spain"],
    ["KR", "South Korea"],
    ["ZA", "South Africa"],
    ["SO", "Somalia"],
    ["", "Somaliland"],
    ["SB", "Solomon Is."],
    ["SK", "Slovakia"],
    ["SI", "Slovenia"],
    ["SG", "Singapore"],
    ["SL", "Sierra Leone"],
    ["SC", "Seychelles"],
    ["RS", "Serbia"],
    ["SN", "Senegal"],
    ["SA", "Saudi Arabia"],
    ["ST", "São Tomé and Principe"],
    ["SM", "San Marino"],
    ["WS", "Samoa"],
    ["VC", "St. Vin. and Gren."],
    ["LC", "Saint Lucia"],
    ["KN", "St. Kitts and Nevis"],
    ["RW", "Rwanda"],
    ["RU", "Russia"],
    ["RO", "Romania"],
    ["QA", "Qatar"],
    ["PT", "Portugal"],
    ["PL", "Poland"],
    ["PH", "Philippines"],
    ["PE", "Peru"],
    ["PY", "Paraguay"],
    ["PG", "Papua New Guinea"],
    ["PA", "Panama"],
    ["PW", "Palau"],
    ["PK", "Pakistan"],
    ["OM", "Oman"],
    ["NO", "Norway"],
    ["KP", "North Korea"],
    ["NG", "Nigeria"],
    ["NE", "Niger"],
    ["NI", "Nicaragua"],
    ["NZ", "New Zealand"],
    ["NU", "Niue"],
    ["CK", "Cook Is."],
    ["NL", "Netherlands"],
    ["AW", "Aruba"],
    ["CW", "Curaçao"],
    ["NP", "Nepal"],
    ["NR", "Nauru"],
    ["NA", "Namibia"],
    ["MZ", "Mozambique"],
    ["MA", "Morocco"],
    ["EH", "W. Sahara"],
    ["ME", "Montenegro"],
    ["MN", "Mongolia"],
    ["MD", "Moldova"],
    ["MC", "Monaco"],
    ["MX", "Mexico"],
    ["MU", "Mauritius"],
    ["MR", "Mauritania"],
    ["MT", "Malta"],
    ["ML", "Mali"],
    ["MV", "Maldives"],
    ["MY", "Malaysia"],
    ["MW", "Malawi"],
    ["MG", "Madagascar"],
    ["MK", "Macedonia"],
    ["LU", "Luxembourg"],
    ["LT", "Lithuania"],
    ["LI", "Liechtenstein"],
    ["LY", "Libya"],
    ["LR", "Liberia"],
    ["LS", "Lesotho"],
    ["LB", "Lebanon"],
    ["LV", "Latvia"],
    ["LA", "Laos"],
    ["KG", "Kyrgyzstan"],
    ["KW", "Kuwait"],
    ["XK", "Kosovo"],
    ["KI", "Kiribati"],
    ["KE", "Kenya"],
    ["KZ", "Kazakhstan"],
    ["JO", "Jordan"],
    ["JP", "Japan"],
    ["JM", "Jamaica"],
    ["IT", "Italy"],
    ["IL", "Israel"],
    ["PS", "Palestine"],
    ["IE", "Ireland"],
    ["IQ", "Iraq"],
    ["IR", "Iran"],
    ["ID", "Indonesia"],
    ["IN", "India"],
    ["IS", "Iceland"],
    ["HU", "Hungary"],
    ["HN", "Honduras"],
    ["HT", "Haiti"],
    ["GY", "Guyana"],
    ["GW", "Guinea-Bissau"],
    ["GN", "Guinea"],
    ["GT", "Guatemala"],
    ["GD", "Grenada"],
    ["GR", "Greece"],
    ["GH", "Ghana"],
    ["DE", "Germany"],
    ["GE", "Georgia"],
    ["GM", "Gambia"],
    ["GA", "Gabon"],
    ["FR", "France"],
    ["PM", "St. Pierre and Miquelon"],
    ["WF", "Wallis and Futuna Is."],
    ["MF", "St-Martin"],
    ["BL", "St-Barthélemy"],
    ["PF", "Fr. Polynesia"],
    ["NC", "New Caledonia"],
    ["", "Fr. S. Antarctic Lands"],
    ["", "Åland"],
    ["FI", "Finland"],
    ["FJ", "Fiji"],
    ["ET", "Ethiopia"],
    ["EE", "Estonia"],
    ["ER", "Eritrea"],
    ["GQ", "Eq. Guinea"],
    ["SV", "El Salvador"],
    ["EG", "Egypt"],
    ["EC", "Ecuador"],
    ["DO", "Dominican Rep."],
    ["DM", "Dominica"],
    ["DJ", "Djibouti"],
    ["GL", "Greenland"],
    ["", "Faeroe Is."],
    ["DK", "Denmark"],
    ["Czechia"],
    ["N. Cyprus"],
    ["Cyprus"],
    ["Cuba"],
    ["Croatia"],
    ["Côte d'Ivoire"],
    ["Costa Rica"],
    ["Dem. Rep. Congo"],
    ["Congo"],
    ["Comoros"],
    ["Colombia"],
    ["China"],
    ["Macao"],
    ["Hong Kong"],
    ["Chile"],
    ["Chad"],
    ["Central African Rep."],
    ["Cabo Verde"],
    ["Canada"],
    ["Cameroon"],
    ["Cambodia"],
    ["Myanmar"],
    ["Burundi"],
    ["Burkina Faso"],
    ["Bulgaria"],
    ["Brunei"],
    ["Brazil"],
    ["Botswana"],
    ["Bosnia and Herz."],
    ["Bolivia","Bhutan"],
    ["Benin"],
    ["Belize"],
    ["Belgium"],
    ["Belarus"],
    ["Barbados"],
    ["Bangladesh"],
    ["Bahrain"],
    ["Bahamas"],
    ["Azerbaijan"],
    ["Austria"],
    ["Australia"],
    ["Indian Ocean Ter."],
    ["Heard I. and McDonald Is."],
    ["Norfolk Island"],
    ["Ashmore and Cartier Is."],
    ["Armenia"],
    ["Argentina"],
    ["Antigua and Barb."],
    ["Angola"],
    ["Andorra"],
    ["Algeria"],
    ["Albania"],
    ["Afghanistan"],
    ["Siachen Glacier"],
    ["Antarctica"],
    ["Sint Maarten"]
]);

